export const beverageWords = [
    "Cinnamon bun",
    "Red velvet",
    "Chocolate cake",
    "Cheesecake",
    "Strawberry shortcake",
    "Carrot cake",
    "Pumpkin pie",
    "Apple pie",
    "Peanut butter cup",
    "Tiramisu",
    "Chocolate truffle",
    "Cookie dough",
    "Mint chocolate chip",
    "Rocky road",
    "Butter pecan",
    "Cookies and cream",
    "Chocolate chip cookie",
    "Oatmeal cookie",
    "Gingerbread",
    "Chocolate fudge brownie",
    "Funfetti",
    "Rainbow sherbet",
    "Toffee",
    "Butterscotch",
    "Maple syrup",
    "Honey",
    "S'mores",
    "Caramel",
    "Peanut butter",
    "Hazelnut",
    "Almond",
    "Cashew",
    "Pecan",
    "Walnut",
    "Macadamia",
    "Pistachio",
    "Coconut",
    "Lemon meringue",
    "Key lime pie",
    "Cherry pie",
    "Blueberry pie",
    "Peach cobbler",
    "Blackberry cobbler",
    "Rhubarb pie",
    "Pecan pie",
    "Sweet potato pie",
    "Pumpkin cheesecake",
    "Chocolate peanut butter pie",
    "Banana cream pie",
    "Lemon curd",
    "Raspberry jam",
    "Strawberry jam",
    "Blueberry jam",
    "Blackberry jam",
    "Cherry jam",
    "Peach jam",
    "Mango jam",
    "Pineapple jam",
    "Guava jam",
    "Grape jam",
    "Apple butter",
    "Pear butter",
    "Plum butter",
    "Apricot butter",
    "Peanut butter and jelly",
    "Cinnamon roll",
    "Doughnut",
    "Croissant",
    "Muffin",
    "Scone",
    "Bagel",
    "Danish",
    "Brioche",
    "Scones",
    "Pastry",
    "Quiche",
    "Cake",
    "Ice cream",
    "Frozen yogurt",
    "Sherbet",
    "Gelato",
    "Custard",
    "Trifle"
]